name: Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: coverage
      run: ./gradlew jacocoTestReport
    - uses: codecov/codecov-action@v1
      with:
        files: ./test/build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true # optional (default = false)
